spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      group-id: listener-example
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
    listener:
      concurrency: 1



